version: 2.1.{build}

shallow_clone: true

image: Visual Studio 2017

environment:
  PYTHON_ROOT: 'C:\Python27'
  BOOST_ROOT: 'C:\Libraries\boost_1_64_0'
  matrix:
    - platform: x64
      ARCH_BITS: 64
    - platform: x86
      ARCH_BITS: 32

configuration:
  - Release
  - Debug

init:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%'

install:
  - cinst cmake

before_build:
  # We rely on teapot for third-party builds.
  - '%PYTHON_ROOT%\python.exe -m pip install teapot'

build_script:
  - '%PYTHON_ROOT%\scripts\teapot.exe build iconv'
  - '%PYTHON_ROOT%\scripts\teapot.exe build openssl'
  - '%PYTHON_ROOT%\scripts\teapot.exe build curl'
  - '%PYTHON_ROOT%\scripts\teapot.exe build miniupnpc'
  - 'mkdir third-party\install\%PLATFORM%\%CONFIGURATION%\include\boost-1_64\boost'
  - 'xcopy /S %BOOST_ROOT%\boost\* third-party\install\%PLATFORM%\%CONFIGURATION%\include\boost-1_64\boost\'
  - 'xcopy /S %BOOST_ROOT%\lib%ARCH_BITS%-msvc-14.1\*vc141-mt-*.lib third-party\install\%PLATFORM%\%CONFIGURATION%\lib\'
  - 'nmake -f Makefile.windows build_%CONFIGURATION%_%PLATFORM%'

branches:
    only:
        - master
