import os


libraries = [
    'kfather',
    'iconvplus',
    'boost_system',
    'iconv',
]

Import('env dirs name')

env = env.Clone()
env.Append(LIBS=libraries)
samples = env.Program(target=os.path.join(str(dirs['bin']), name), source=env.RGlob('.', ['*.cpp']))

Return('samples')
