"""A sample SConscript file."""

libraries = []

### YOU SHOULD NEVER CHANGE ANYTHING BELOW THIS LINE ###

Import('env project')

sample_project = project.Sample(libraries)
sample = env.FreelanProject(sample_project)

env.Alias('sample_' + sample_project.name, sample)

Return('sample')
