"""A sample SConscript file."""

libraries = []

### YOU SHOULD NEVER CHANGE ANYTHING BELOW THIS LINE ###

Import('env project')

sample = env.FreelanProject(project.Sample(libraries))

Return('sample')
