##
# libcryptoplus tests build file.
#

### YOU SHOULD NEVER CHANGE ANYTHING BELOW THIS LINE ###

Import('env', 'module', 'libraries')

import os, subprocess

try:
	env['CXXFLAGS'].append(subprocess.Popen(['cppunit-config', '--cflags'], stdout=subprocess.PIPE).communicate()[0].split())
except:
	pass

cpppath = [os.path.join('../include', module)]
libpath = [os.path.join('../lib')]

source = Glob('src/*.cpp')
libs = [libraries[2], 'crypto']

try:
	libs.append(subprocess.Popen(['cppunit-config', '--libs'], stdout=subprocess.PIPE).communicate()[0].split())
except:
	pass

# Build the test
tests = env.Program('tests', source, CPPPATH = cpppath, LIBPATH = libpath, LIBS = libs)

# Aliases
env.Alias('build-tests', tests)
run_tests = env.Alias('run-tests', [tests], tests[0].abspath)

env.AlwaysBuild(run_tests);

Return('run_tests')
