"""The SConstruct file"""

name = 'freelan'
product_name = 'FreeLAN'
major = '1'
minor = '0'

# You should not need to modify anything below this line

import os

from freelan.build_tools import Environment

env = Environment(ENV = os.environ.copy(), ARGUMENTS = ARGUMENTS)

defines = {
    'NAME': name,
    'VERSION': major + '.' + minor,
    'ARCH': env.arch
}

installer = env.INNOSetup(source = 'freelan.iss', ISCC_DEFINES = defines)
