"""The SConstruct file"""

name = 'freelan'
product_name = 'FreeLAN'
major = '1'
minor = '1'

# You should not need to modify anything below this line

import os

from freelan.buildtools import Environment

env = Environment(ENV = os.environ.copy(), ARGUMENTS = ARGUMENTS)

defines = {
    'NAME': name,
    'VERSION': major + '.' + minor,
    'ARCH': env.arch,
    'XARCH': 'x64' if env.arch == 'amd64' else 'x86',
}

installer = env.INNOSetup(source = 'freelan.iss', ISCC_DEFINES = defines)
