#!/bin/bash

CURRENT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $# -ne 1 ]
then
    echo "Missing argument." >&2
    echo "Usage: init_archives <directory>" >&2
fi

DIR="$1"
ITEMS="$(ls ${DIR} -p | grep / | cut -f1 -d/)"

for ITEM in ${ITEMS}
do
    PROJECT_NAME=$(python -c "print '${ITEM}'[:'${ITEM}'.rindex('-')]")
    PROJECT_VERSION=$(python -c "print '${ITEM}'['${ITEM}'.rindex('-') + 1:]")

    ${CURRENT_DIR}/get_archive ${PROJECT_NAME} ${PROJECT_VERSION} ${DIR}
done
