"""A SConstruct file to build Debian packages."""

import os

from freelan.build_tools import Environment

env = Environment(ENV = os.environ.copy(), ARGUMENTS = ARGUMENTS)

# Add the packaging tools
env.Tool('packaging')

archive = env.GitExtract(Dir('.'), Dir('../../libcryptoplus'))
source = env.GitExtract(Dir('.'), Dir('../../libcryptoplus'), GIT_EXTRACT_FORMAT='tar')
copy = env.Command('libcryptoplus_master.orig.tar.gz', archive, Copy('$TARGET', '$SOURCE'))
