Import('env dirs')

env = env.Clone()

local_include_dir = Dir('include/iconvplus')

env.Prepend(CPPPATH=[local_include_dir])

includes = env.RInstall(dirs['root'], local_include_dir, ['*.hpp'])

library = env.StaticLibrary(target=dirs['lib'], source=env.RGlob('src', '*.cpp'))

Return('library includes')
