import os
import sys


Import('env dirs name')

env = env.Clone()

if sys.platform.startswith('darwin'):
    env['CXXFLAGS'].append('-DBOOST_ASIO_DISABLE_KQUEUE')

local_include_dir = Dir(os.path.join('include', name))
env.Prepend(CPPPATH=[local_include_dir])

sources = list(sorted(set(env.RGlob('src', '*.cpp')) - set(env.RGlob(os.path.join('src', 'windows'), '*.cpp'))))

includes = env.RInstall(dirs['root'], local_include_dir, ['*.hpp'])
library = env.StaticLibrary(target=os.path.join(str(dirs['lib']), name), source=list(sources))

Return('library includes')
