import os
import sys

libraries = [
    'asiotap',
    'boost_system',
    'boost_iostreams',
]

if sys.platform.startswith('linux'):
    libraries.append('pthread')

Import('env dirs name')

env = env.Clone()
env.Append(LIBS=libraries)
samples = env.Program(target=os.path.join(str(dirs['bin']), name), source=env.RGlob('.', ['*.cpp']))

Return('samples')
