import os


libraries = [
    'asiotap',
    'executeplus',
    'boost_system',
    'boost_iostreams',
]

Import('env dirs name')

env = env.Clone()
env.Append(LIBS=libraries)
samples = env.Program(target=os.path.join(str(dirs['bin']), name), source=env.RGlob('.', ['*.cpp']))

Return('samples')
