"""A sample SConscript file."""

import os

Import('env project')

### YOU SHOULD NEVER CHANGE ANYTHING BELOW THIS LINE ###

sample_project = project.Sample()
sample_project.libraries.append('boost_thread')
sample = env.FreelanProject(sample_project)

env.Alias('sample_' + sample_project.name, sample)

Return('sample')
