import os
import sys


libraries = [
    'iconvplus',
    'boost_system',
]

if sys.platform.startswith('darwin') or sys.platform.startswith('openbsd'):
    libraries.extend([
        'iconv',
    ])

Import('env dirs name')

env = env.Clone()
env.Append(LIBS=libraries)
samples = env.Program(target=os.path.join(str(dirs['bin']), name), source=env.RGlob('.', ['*.cpp']))

Return('samples')
