import os
import sys


libraries = [
    'asiotap',
    'executeplus',
    'boost_system',
    'boost_iostreams',
    'pthread',
]

if sys.platform.startswith('linux'):
    libraries.extend([
        'netlinkplus',
    ])

Import('env dirs name')

env = env.Clone()
env.Append(LIBS=libraries)
samples = env.Program(target=os.path.join(str(dirs['bin']), name), source=env.RGlob('.', ['*.cpp']))

Return('samples')
