import os
import sys


libraries = [
    'fscp',
    'cryptoplus',
    'boost_system',
    'crypto',
    'miniupnpcplus',
    'miniupnpc',
]

if sys.platform.startswith('darwin'):
    libraries.extend([
        'boost_thread-mt',
    ])
else:
    libraries.extend([
        'boost_thread',
    ])

if sys.platform.startswith('linux'):
    libraries.extend([
        'pthread',
    ])

Import('env dirs name')

env = env.Clone()
env.Append(LIBS=libraries)
samples = env.Program(target=os.path.join(str(dirs['bin']), name), source=env.RGlob('.', ['*.cpp']))

Return('samples')
