##
# libcryptopen build file.
#
sample = 'hmac'
module = 'cryptopen'

### YOU SHOULD NEVER CHANGE ANYTHING BELOW THIS LINE ###

import sys, os

include_path = os.path.join('..', '..', 'include', module)
lib_path = os.path.join('..', '..', 'lib')
source = Glob('*.cpp')
cpppath = [include_path]
libpath = [lib_path]
libs = [module]

# Import the customized environment
sys.path.append(os.path.abspath('../../scons'))
import environment

env = environment.Environment(path = '../..', ENV = os.environ.copy())

# Build the sample
sample = env.Sample(sample, source, CPPPATH = cpppath, LIBPATH = libpath, LIBS = libs)

# Aliases
env.Alias('build', sample)

# Default
Default('build')
